version: '3'
services:
  springboot:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: "store-management-back"
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks: ["mongo-network"]

  mongodb:
    restart: unless-stopped
    container_name: "store-management-mongodb"
    image: mongo:latest
    ports:
      - 27017:27017
    networks: ["mongo-network"]

networks:
  mongo-network:
    driver: bridge